import { z } from 'zod';

// because of a limitation of TypeScript, type can't be statically inferred
export type BandalartCell = z.infer<typeof BaseBandalartCellSchema> & {
  children: BandalartCell[];
};
const BaseBandalartCellSchema = z.object({
  key: z.string({ description: '반다라트 셀의 키' }),
  isCompleted: z.boolean({ description: '달성 여부' }),
  completionRatio: z.number({ description: '달성률' }),
  dueDate: z
    .string({ description: '달성 목표일' })
    .datetime({ offset: true })
    .nullable(),
  title: z.string({ description: '목표 이름' }).nullable(),
  description: z.string({ description: '메모' }).nullable(),
  parentKey: z.string({ description: '부모 셀의 키' }).nullable(),
});
export const BandalartCellSchema: z.ZodType<BandalartCell> =
  BaseBandalartCellSchema.extend({
    children: z.lazy(() => z.array(BandalartCellSchema)),
  });

export const mockBandalartCells: BandalartCell = {
  key: '1',
  isCompleted: false,
  completionRatio: 44,
  title: '발전하는 예진',
  description: '',
  dueDate: '',
  parentKey: null,
  children: [
    {
      key: '2',
      parentKey: '1',
      isCompleted: false,
      completionRatio: 0,
      title: '건강',
      description: '',
      dueDate: '',
      children: [
        {
          key: '6',
          parentKey: '2',
          isCompleted: false,
          completionRatio: 0,
          title: '헬스장 주 3회 가기',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '7',
          parentKey: '2',
          isCompleted: true,
          completionRatio: 0,
          title: '하루 물 2L 마시기',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '8',
          parentKey: '2',
          isCompleted: true,
          completionRatio: 0,
          title: '일주일에 2번 이상 산책',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '9',
          parentKey: '2',
          isCompleted: false,
          completionRatio: 0,
          title: '매일 아침 스트레칭',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '10',
          parentKey: '2',
          isCompleted: true,
          completionRatio: 0,
          title: '12시 전에 취침',
          description: '',
          dueDate: '',
          children: [],
        },
      ],
    },
    {
      key: '3',
      parentKey: '1',
      isCompleted: true,
      completionRatio: 0,
      title: '성장',
      description: '',
      dueDate: '',
      children: [
        {
          key: '11',
          parentKey: '3',
          isCompleted: true,
          completionRatio: 0,
          title: '한 달에 한 권 이상 독서',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '12',
          parentKey: '3',
          isCompleted: true,
          completionRatio: 0,
          title: '네트워킹 모임 참여',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '13',
          parentKey: '3',
          isCompleted: true,
          completionRatio: 0,
          title: '사이드 프로젝트 2개',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '14',
          parentKey: '3',
          isCompleted: true,
          completionRatio: 0,
          title: '뉴스레터 읽기',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '15',
          parentKey: '3',
          isCompleted: true,
          completionRatio: 0,
          title: '하루 1시간 아티클 읽기',
          description: '',
          dueDate: '',
          children: [],
        },
      ],
    },
    {
      key: '4',
      parentKey: '1',
      isCompleted: false,
      completionRatio: 0,
      title: '재테크',
      description: '',
      dueDate: '',
      children: [
        {
          key: '16',
          parentKey: '4',
          isCompleted: false,
          completionRatio: 0,
          title: '부수입 월 500만원',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '17',
          parentKey: '4',
          isCompleted: true,
          completionRatio: 0,
          title: '적금 2천만원 저축',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '18',
          parentKey: '4',
          isCompleted: false,
          completionRatio: 0,
          title: '고정지출 20만원 줄이기',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '19',
          parentKey: '4',
          isCompleted: false,
          completionRatio: 0,
          title: '배달음식 5만원 이하',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '20',
          parentKey: '4',
          isCompleted: true,
          completionRatio: 0,
          title: '주식 수익 10% 달성',
          description: '',
          dueDate: '',
          children: [],
        },
      ],
    },
    {
      key: '5',
      parentKey: '1',
      isCompleted: false,
      completionRatio: 0,
      title: '취미',
      description: '',
      dueDate: '',
      children: [
        {
          key: '21',
          parentKey: '5',
          isCompleted: false,
          completionRatio: 0,
          title: '등산 10번',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '22',
          parentKey: '5',
          isCompleted: false,
          completionRatio: 0,
          title: '기타 배우기',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '23',
          parentKey: '5',
          isCompleted: false,
          completionRatio: 0,
          title: '마라톤 10km 완주',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '24',
          parentKey: '5',
          isCompleted: false,
          completionRatio: 0,
          title: '필라테스 주 1회',
          description: '',
          dueDate: '',
          children: [],
        },
        {
          key: '25',
          parentKey: '5',
          isCompleted: false,
          completionRatio: 0,
          title: '베이킹 클래스 듣기',
          description: '',
          dueDate: '',
          children: [],
        },
      ],
    },
  ],
};
